Repository CartoDB/cartodb, pull requests merged in 2018-05, with the labels that each got.

#13901 Sync overviews privileges to those of the base table
  Makefile
  NEWS.md
  app/models/carto/api_key.rb
  app/models/table.rb
  app/models/table/privacy_manager.rb
  app/models/user/db_service.rb
  app/services/carto/overviews_service.rb
  app/services/carto/table_and_friends.rb
  lib/carto/db/sql_interface.rb
  spec/connectors/importer_overviews_spec.rb
  spec/lib/carto/db/sql_interface_spec.rb
  spec/support/factories/organizations.rb
Labels: bug

#13933 Add batch size to rake
  lib/tasks/redis_keys.rake
Labels: Backend

#13913 [WIP] Fix builder notification persistance at account and profile pages
  NEWS.md
  app/views/admin/users/account.html.erb
  app/views/admin/users/profile.html.erb
Labels: Frontend

#13942 [GDPR] password changes
  NEWS.md
  app/controllers/admin/users_controller.rb
  app/controllers/carto/api/users_controller.rb
  app/models/user.rb
  spec/models/user_spec.rb
  spec/requests/admin/organization_users_controller_spec.rb
  spec/requests/admin/users_controller_spec.rb
  spec/requests/carto/api/organization_users_controller_spec.rb
  spec/requests/carto/api/users_controller_spec.rb
Labels: major-priority

#13968 Tab-pane improvements in `Size`
  app/assets/stylesheets/editor-3/_forms.scss
  app/assets/stylesheets/editor-3/fill/_fill.scss
  lib/assets/javascripts/builder/components/form-components/editors/fill-color/inputs/input-color-by-value.tpl
  lib/assets/javascripts/builder/components/form-components/editors/size/size.js
  lib/assets/javascripts/builder/components/form-components/editors/size/size.tpl
  lib/assets/javascripts/builder/components/tab-pane/create-radio-labels-tab-pane.js
  lib/assets/javascripts/builder/editor/style/style-form/style-form-dictionary/fill-size.js
  lib/assets/javascripts/locale/en.json
  lib/assets/test/spec/builder/components/tab-pane/create-radio-labels-tab-pane.spec.js
Labels: Frontend

#13977 Improvements in 'Size by Value'
  app/assets/stylesheets/editor-3/_forms.scss
  app/assets/stylesheets/editor-3/fill/_fill.scss
  lib/assets/javascripts/builder/components/form-components/_constants/_fill.js
  lib/assets/javascripts/builder/components/form-components/editors/fill-color/fill-color.js
  lib/assets/javascripts/builder/components/form-components/editors/fill-color/inputs/input-color-by-value.js
  lib/assets/javascripts/builder/components/form-components/editors/fill-color/inputs/input-color-fixed.js
  lib/assets/javascripts/builder/components/form-components/editors/fill/input-color/input-color-dialog-content.js
  lib/assets/javascripts/builder/components/form-components/editors/fill/input-color/input-color.js
  lib/assets/javascripts/builder/components/form-components/editors/fill/input-number/input-number-dialog-content.js
  lib/assets/javascripts/builder/components/form-components/editors/size/size-by-value-content-view.js
  lib/assets/javascripts/builder/components/form-components/editors/size/size-by-value-content-view.tpl
  lib/assets/javascripts/builder/components/form-components/editors/size/size-by-value-view.js
  lib/assets/javascripts/builder/components/form-components/editors/size/size-by-value-view.tpl
  lib/assets/javascripts/builder/components/form-components/editors/size/size-value-view.tpl
  lib/assets/javascripts/builder/components/form-components/editors/size/size.js
  lib/assets/javascripts/builder/components/tab-pane/tab-pane-radio-label-view.js
  lib/assets/javascripts/builder/components/tab-pane/tab-pane-radio-label.tpl
  lib/assets/javascripts/builder/editor/style/style-form/style-form-dictionary/fill.js
  lib/assets/javascripts/builder/editor/widgets/widgets-form/schema/widgets-form-base-schema-model.js
  lib/assets/javascripts/builder/editor/widgets/widgets-form/schema/widgets-form-time-series-schema-model.js
  lib/assets/javascripts/locale/en.json
  lib/assets/test/spec/builder/components/form-components/editors/fill.spec.js
Labels: Frontend

#13989 Add stroke size
  lib/assets/javascripts/builder/components/form-components/editors/size/size-by-value-view.js
  lib/assets/javascripts/builder/components/form-components/editors/size/size.js
  lib/assets/javascripts/builder/editor/style/style-content-view.js
  lib/assets/javascripts/builder/editor/style/style-form/style-form-dictionary/fill-size.js
  lib/assets/javascripts/builder/editor/style/style-form/style-form-dictionary/stroke-size.js
  lib/assets/javascripts/builder/editor/style/style-form/style-properties-form/style-shape-properties-form-model.js
  lib/assets/javascripts/locale/en.json
Labels: Frontend

#13990 Change copy on twitter connector deprecation
  NEWS.md
  lib/assets/javascripts/cartodb/common/dialogs/create/footer/guessing_toggler.jst.ejs
  lib/assets/javascripts/locale/en.json
  lib/assets/test/spec/cartodb/dashboard/dialogs/create/footer/guessing_toggler.spec.js
Labels: Frontend

#13959 [GDPR] add password change controller and page
  Makefile
  NEWS.md
  app/controllers/api/application_controller.rb
  app/controllers/application_controller.rb
  app/controllers/password_change_controller.rb
  app/controllers/sessions_controller.rb
  app/models/carto/user.rb
  app/models/user.rb
  app/views/password_change/edit.html.erb
  config/initializers/warden.rb
  config/routes.rb
  spec/requests/password_change_controller_spec.rb
  spec/requests/warden_spec.rb
Labels: major-priority

#13995 Allow deleting locked users
  app/controllers/admin/users_controller.rb
  app/views/admin/users/lockout.html.erb
  spec/requests/user_state_spec.rb
Labels: Backend

#14003 Migrate more stuff
  NEWS.md
  app/models/carto/connector_configuration.rb
  app/models/carto/organization.rb
  app/models/carto/user.rb
  app/services/carto/organization_metadata_export_service.rb
  app/services/carto/user_metadata_export_service.rb
  lib/carto/export/connector_configuration_exporter.rb
  spec/services/carto/organization_metadata_export_service_spec.rb
  spec/services/carto/user_metadata_export_service_spec.rb
Labels: Backend

#14007 Rake fix permissions
  NEWS.md
  lib/tasks/permissions.rake
Labels: Backend
