Repository CartoDB/cartodb, pull requests merged in 2018-03, with the labels that each got.

#13614 Mobile Apps dashboard migration
  app/assets/stylesheets/mobile_apps/mobile_apps_plan.css.scss
  app/controllers/carto/admin/mobile_apps_controller.rb
  app/controllers/carto/api/mobile_app_presenter.rb
  app/views/carto/admin/mobile_apps/_no_mobile_apps.html.erb
  app/views/carto/admin/mobile_apps/index.html.erb
  app/views/carto/admin/mobile_apps/new.html.erb
  app/views/carto/admin/mobile_apps/show.html.erb
  config/application.rb
  lib/assets/javascripts/dashboard/components/app-platforms-legends.js
  lib/assets/javascripts/dashboard/components/icon-selector/icon-selector-view.js
  lib/assets/javascripts/dashboard/components/icon-selector/icon-selector.tpl
  lib/assets/javascripts/dashboard/data/asset-model.js
  lib/assets/javascripts/dashboard/mobile-apps.js
  lib/assets/javascripts/dashboard/views/mobile-apps/delete-mobile-app/delete-mobile-app-view.js
  lib/assets/javascripts/dashboard/views/mobile-apps/delete-mobile-app/delete-mobile-app.tpl
  lib/assets/javascripts/dashboard/views/mobile-apps/header-view-model.js
  package.json
  webpack/dashboard/webpack.dev.config.js
Labels: do not merge yet, editor migration

#13608 Data library dashboard migration
  NEWS.md
  app/assets/stylesheets/common/dropdown.css.scss
  app/controllers/data_library_controller.rb
  app/views/layouts/data_library.html.erb
  config/application.rb
  lib/assets/javascripts/dashboard/components/dropdown/dropdown-base-view.js
  lib/assets/javascripts/dashboard/components/user-info/dropdown-view.js
  lib/assets/javascripts/dashboard/components/user-info/user-info-view.js
  lib/assets/javascripts/dashboard/data-library.js
  lib/assets/javascripts/dashboard/data/datasets-collection.js
  lib/assets/javascripts/dashboard/data/visualization-model.js
  lib/assets/javascripts/dashboard/data/visualization-order-model.js
  lib/assets/javascripts/dashboard/data/visualizations-collection.js
  lib/assets/javascripts/dashboard/views/data-library/content/content-view.js
  lib/assets/javascripts/dashboard/views/data-library/content/error-template.tpl
  lib/assets/javascripts/dashboard/views/data-library/content/list/dataset-item-view.js
  lib/assets/javascripts/dashboard/views/data-library/content/list/dataset-item.tpl
  lib/assets/javascripts/dashboard/views/data-library/content/list/list-view.js
  lib/assets/javascripts/dashboard/views/data-library/content/list/placeholder-item-template.tpl
  lib/assets/javascripts/dashboard/views/data-library/content/list/placeholder_item_view.js
  lib/assets/javascripts/dashboard/views/data-library/content/loader-template.tpl
  lib/assets/javascripts/dashboard/views/data-library/content/more-template.tpl
  lib/assets/javascripts/dashboard/views/data-library/content/no-results-template.tpl
  lib/assets/javascripts/dashboard/views/data-library/data-library-view.js
  lib/assets/javascripts/dashboard/views/data-library/filters/dropdown/dropdown-view.js
  lib/assets/javascripts/dashboard/views/data-library/filters/dropdown/dropdown.tpl
  lib/assets/javascripts/dashboard/views/data-library/filters/filters-view.js
  lib/assets/javascripts/dashboard/views/data-library/filters/filters.tpl
  lib/assets/javascripts/dashboard/views/data-library/header/header-view.js
  lib/assets/javascripts/dashboard/views/data-library/header/header.tpl
  lib/assets/test/spec/dashboard/data/datasets-collection.spec.js
  lib/assets/test/spec/dashboard/data/visualization-model.spec.js
  lib/assets/test/spec/dashboard/data/visualization-order-model.spec.js
  lib/assets/test/spec/dashboard/data/visualizations-collection.spec.js
  lib/assets/test/spec/dashboard/views/data-library/content/content-view.spec.js
  lib/assets/test/spec/dashboard/views/data-library/content/list/dataset-item-view.spec.js
  lib/assets/test/spec/dashboard/views/data-library/content/list/list-view.spec.js
  lib/assets/test/spec/dashboard/views/data-library/data-library-view.spec.js
  lib/assets/test/spec/dashboard/views/data-library/filters/dropdown/dropdown-view.spec.js
  lib/assets/test/spec/dashboard/views/data-library/filters/filters-view.spec.js
  lib/assets/test/spec/dashboard/views/data-library/header/header-view.spec.js
  lib/assets/test/spec/fixtures/dashboard/config-model.fixture.js
  webpack/dashboard/webpack.dev.config.js
  webpack/dashboard/webpack.prod.config.js
Labels: editor migration

#13641 Signup dashboard migration
  NEWS.md
  app/views/sessions/new.html.erb
  app/views/shared/signup_confirmation.html.erb
  app/views/signup/signup.html.erb
  config/application.rb
  lib/assets/javascripts/dashboard/confirmation.js
  lib/assets/javascripts/dashboard/confirmation/confirmation-info.tpl
  lib/assets/javascripts/dashboard/confirmation/confirmation-model.js
  lib/assets/javascripts/dashboard/confirmation/confirmation-view.js
  lib/assets/javascripts/dashboard/sessions.js
  webpack/dashboard/webpack.dev.config.js
  webpack/dashboard/webpack.prod.config.js
Labels: editor migration

#13728 Similar notifications should be stacked
  NEWS.md
  lib/assets/javascripts/builder/components/modals/add-widgets/add-widgets-view.js
  lib/assets/javascripts/builder/components/modals/add-widgets/category/category-option-model.js
  lib/assets/javascripts/builder/components/modals/add-widgets/formula/formula-option-model.js
  lib/assets/javascripts/builder/components/modals/add-widgets/histogram/histogram-option-model.js
  lib/assets/javascripts/builder/components/modals/add-widgets/time-series/time-series-option-model.js
  lib/assets/javascripts/builder/components/notifier/notifier-collection.js
  lib/assets/javascripts/builder/components/notifier/notifier.js
  lib/assets/javascripts/builder/data/user-actions.js
  lib/assets/javascripts/builder/data/widget-definitions-collection.js
  lib/assets/javascripts/builder/editor/layers/layer-content-views/data/data-content-view.js
  lib/assets/javascripts/builder/editor/layers/layers-view.js
  lib/assets/javascripts/builder/widgets-notifications.js
  lib/assets/javascripts/locale/en.json
  lib/assets/test/spec/builder/components/modals/add-widgets/category-option-model.spec.js
  lib/assets/test/spec/builder/components/modals/add-widgets/formula-option-model.spec.js
  lib/assets/test/spec/builder/components/modals/add-widgets/histogram-option-model.spec.js
  lib/assets/test/spec/builder/components/modals/add-widgets/time-series-option-model.spec.js
  lib/assets/test/spec/builder/components/notifier/notifier-collection.spec.js
  lib/assets/test/spec/builder/components/notifier/notifier.spec.js
  lib/assets/test/spec/builder/data/widget-definitions-collection.spec.js
  lib/assets/test/spec/builder/editor/layers/layers-view.spec.js
  lib/assets/test/spec/builder/widgets-notifications.spec.js
  npm-shrinkwrap.json
Labels: Frontend

#13758 Onpremises style issues IE
  NEWS.md
  app/assets/stylesheets/common/dialog.css.scss
  app/assets/stylesheets/common/forms/checkbox.css.scss
  app/assets/stylesheets/editor-3/_forms.scss
  lib/assets/javascripts/cartodb/common/dialogs/export/export_view.js
  lib/assets/javascripts/cartodb/common/dialogs/export/public_export_template.jst.ejs
  lib/assets/javascripts/cartodb/common/dialogs/export/public_export_view.js
  lib/assets/javascripts/cartodb/common/templates/loading.jst.ejs
  lib/assets/javascripts/locale/en.json
  package.json
Labels: Frontend

#13776 Revert dialog height
  app/assets/stylesheets/common/dialog.css.scss
Labels: Frontend, bug
