Repository CartoDB/cartodb, pull requests merged in 2018-07, with the labels that each got.

#14137 Fix wrong style after creating a feature
  .gitignore
  NEWS.md
  lib/assets/javascripts/builder/components/input-color/input-qualitative-ramps/main-view.js
  lib/assets/javascripts/builder/editor/layers/edit-feature-content-view.js
  lib/assets/javascripts/builder/editor/widgets/time-series-query-model.js
  lib/assets/test/spec/builder/components/form-components/editors/fill/input-color/input-qualitative-ramps/main-view.spec.js
  package.json
Labels: Frontend

#14145 Fix category name overflow when styling by value
  NEWS.md
  lib/assets/javascripts/builder/components/input-color/input-color-picker/input-color-picker-header.tpl
Labels: Frontend

#14157 S1572 sync duplicated indices
  NEWS.md
  lib/carto/importer/table_setup.rb
  spec/models/synchronization/member_spec.rb
Labels: response-team

#14173 Add headers for caching
  NEWS.md
  app/controllers/carto/builder/public/embeds_controller.rb
  spec/requests/carto/builder/public/embeds_controller_spec.rb
Labels: blocked

#14197 Fix disconnect from external sources for org users (gdrive, box and dropbox)
  NEWS.md
  lib/assets/javascripts/dashboard/components/service-item/service-item-view.js
  lib/assets/javascripts/dashboard/views/account/service-disconnect-dialog/service-disconnect-dialog-view.js
  lib/assets/test/spec/dashboard/views/account/service-disconnect-dialog-view.spec.js
  package.json
Labels: Blocking a client, Frontend, bug

#14201 Fix color legends allowed for boolean attributes
  NEWS.md
  lib/assets/javascripts/builder/data/layer-definition-model.js
  lib/assets/javascripts/builder/deep-insights-integration/legend-manager.js
  lib/assets/javascripts/builder/editor/layers/layer-content-views/legend/color/legend-color-types.js
  lib/assets/javascripts/builder/editor/layers/layer-content-views/legend/legend-types.js
  lib/assets/javascripts/builder/editor/layers/layer-content-views/legend/size/legend-size-types.js
  lib/assets/javascripts/builder/editor/style/style-definition-model.js
  lib/assets/test/spec/builder/editor/layers/layer-content-view/legend/color/legend-color-types.spec.js
  lib/assets/test/spec/builder/editor/layers/layer-content-view/legend/legend-content-view.spec.js
  lib/assets/test/spec/builder/editor/layers/layer-content-view/legend/legends-view.spec.js
  package.json
Labels: Frontend, bug
