Repository CartoDB/cartodb, pull requests merged in 2018-04, with the labels that each got.

#13815 13814 secondary redis
  NEWS.md
  app/services/carto/redis_export_service.rb
  config/app_config.yml.sample
  config/initializers/redis.rb
  lib/redis_factory.rb
Labels: Backend

#13847 Fix bottom extra space in legends
  NEWS.md
  app/assets/stylesheets/deep-insights/themes/scss/map/_embed.scss
  npm-shrinkwrap.json
Labels: Design, Frontend

#13855 Show overlap options on solid styled points
  NEWS.md
  lib/assets/javascripts/builder/editor/style/style-form/style-form-default-model.js
  lib/assets/test/spec/builder/editor/style/style-form/style-form-default-model.spec.js
Labels: Frontend

#13912 Fix require for carto.js at some specs
  lib/assets/test/spec/builder/embed-integrations.spec.js
  lib/assets/test/spec/deep-insights/widgets/time-series/torque-histogram-view.spec.js
  lib/assets/test/spec/deep-insights/widgets/time-series/torque-time-slider-view.spec.js
Labels: Frontend
