Repository CartoDB/cartodb, pull requests merged in 2018-06, with the labels that each got.

#14049 Split size & color - Remove 'Category' in color by value from some aggregation modes
  lib/assets/javascripts/builder/components/form-components/editors/fill-color/fill-color-by-value-view.js
  lib/assets/javascripts/builder/components/form-components/editors/fill-color/fill-color.js
  lib/assets/javascripts/builder/components/form-components/editors/fill-color/inputs/input-color-by-value.js
  lib/assets/javascripts/builder/components/input-color/input-color-value-content-view.js
  lib/assets/javascripts/builder/components/input-color/input-quantitative-ramps/main-view.js
  lib/assets/javascripts/builder/editor/style/style-form/style-form-dictionary/fill-color.js
  lib/assets/test/spec/builder/editor/style/style-form/style-form-components-dictionary.spec.js
Labels: Frontend

#13884 Use regular expressions for function matching
  NEWS.md
  services/user-mover/import_user.rb
  services/user-mover/legacy_functions.rb
  spec/models/carto/user_migration_spec.rb
Labels: blocked

#14013 Redirect to login if trying to access another user private pages
  NEWS.md
  app/controllers/admin/visualizations_controller.rb
  lib/assets/javascripts/dashboard/account.js
  lib/assets/javascripts/dashboard/dashboard.js
  lib/assets/javascripts/dashboard/helpers/parse-domains.js
  lib/assets/javascripts/dashboard/helpers/redirector.js
  lib/assets/javascripts/dashboard/profile.js
  lib/assets/javascripts/dashboard/statics/helpers/url.js
  lib/assets/javascripts/dashboard/statics/index.jst.ejs
  lib/assets/javascripts/dashboard/statics/static.js
  lib/assets/test/spec/dashboard/helpers/redirector.spec.js
  lib/build/files/webpack_files.js
  webpack/webpack.dev.config.js
  webpack/webpack.prod.config.js
Labels: Frontend

#14116 Log resque errors
  NEWS.md
  config/initializers/load_resque.rb
  lib/cartodb/logger.rb
Labels: Backend
