Repository CartoDB/cartodb, pull requests merged in 2019-07, with the labels that each got.

#15006 remove some ghost tables rollbar logging
  NEWS.md
  lib/carto/ghost_tables_manager.rb
Labels: needs review, rt-backend

#15005 document limits and raise error if ArcGIS response times out
  NEWS.md
  doc/developer-center/import-api/guides/06-the-arcgis-connector.md
  services/datasources/lib/datasources/url/arcgis.rb
  spec/models/data_import_spec.rb
Labels: rt-backend

#15007 document limit gdrive
  doc/developer-center/import-api/guides/08-importing-geospatial-data.md
Labels: needs review, rt-backend

#15008 Document normalize
  NEWS.md
  doc/developer-center/import-api/guides/06-the-arcgis-connector.md
  doc/developer-center/import-api/guides/09-column-names-normalization.md
Labels: needs review, rt-backend

#15026 Set maps and datasets filter to shared when user is viewer
  NEWS.md
  lib/assets/javascripts/new-dashboard/pages/Data.vue
  lib/assets/javascripts/new-dashboard/pages/Home/Home.vue
  lib/assets/javascripts/new-dashboard/pages/Maps.vue
Labels: Frontend

#14963 [Signup fields I] Migration
  db/migrate/20190612101226_add_signup_fields_to_users.rb
  spec/services/carto/user_metadata_export_service_spec.rb
Labels: blocked, do not merge yet

#15033 Fix user presenter
  NEWS.md
  app/models/carto/user.rb
Labels: needs review
