Repository CartoDB/cartodb, pull requests merged in 2020-03, with the labels that each got.

#14605 Add new task to help carto.js v3 development
  Gruntfile.js
  lib/build/tasks/watch.js
  package.json
Labels: rt-frontend

#15527 bump netaddr
  Gemfile.lock
Labels: needs review

#15536 [support#2394] Fix Google Maps Load
  NEWS.md
  app/controllers/carto/builder/datasets_controller.rb
  app/controllers/carto/builder/public/embeds_controller.rb
  app/controllers/carto/builder/visualizations_controller.rb
  app/views/admin/visualizations/public_dataset.html.erb
  app/views/admin/visualizations/public_map.html.erb
  app/views/admin/visualizations/show.html.erb
  app/views/carto/builder/datasets/show.html.erb
  app/views/carto/builder/public/embeds/show.html.erb
  app/views/carto/builder/visualizations/show.html.erb
  spec/requests/carto/builder/visualizations_controller_spec.rb
Labels: rt-backend

#15559 Fixed wrong url
  NEWS.md
  app/views/admin/shared/_public_footer.html.erb
  lib/assets/javascripts/cartodb/public/views/public_footer.jst.ejs
  package-lock.json
  package.json
Labels: Frontend
