Repository CartoDB/cartodb, pull requests merged in 2020-05, with the labels that each got.

#15665 scrub Rollbar data
  NEWS.md
  app/models/carto/helpers/user_commons.rb
  lib/cartodb/logger.rb
Labels: security

#15670 fix raise exception
  app/controllers/application_controller.rb
  lib/carto/authentication_manager.rb
Labels: needs review

#15671 lastlogin hubspot
  NEWS.md
  app/models/concerns/cartodb_central_synchronizable.rb
  config/initializers/warden.rb
Labels: needs review

#15674 Speed up ghost table manager checks
  NEWS.md
  lib/carto/ghost_tables_manager.rb
Labels: response-team

#15678 v1/viz: Stop returning the db_size_in_bytes value
  NEWS.md
  app/controllers/carto/api/permission_presenter.rb
  app/controllers/carto/api/user_table_presenter.rb
  app/controllers/carto/api/visualization_presenter.rb
  spec/requests/carto/api/visualizations_controller_spec_part_2.rb
Labels: response-team
